//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class torneos
    {
        public decimal idTorneo { get; set; }
        public string nombre_Usuario { get; set; }
        public string nombreTorneo { get; set; }
        public decimal noJugadores { get; set; }
    }
}
